[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\instrument_addon'

[dependencies.Instrument-Custom-Device-Classes]
libraries = ['Protections.lvlibp', 'Protocols.lvlibp']
copy_location = 'Source'

[projects.windows]
path = 'Source\Instrument Addon.lvproj'

[projects.linux32]
path = 'Source\Instrument Addon - Linux32.lvproj'

[projects.linux64]
path = 'Source\Instrument Addon - Linux64.lvproj'

[projects.api]
path = 'Source\Instrument Addon SysDef API.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'pharlap'

[[build.steps]]
name = 'Workspace Object'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Workspace Object'
dependency_target = 'pharlap'

[[build.steps]]
name = 'Workspace Tool'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Workspace Tool'
dependency_target = 'pharlap'

[[build.steps]]
name = 'Host API'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Host API'
dependency_target = 'pharlap'

[[build.steps]]
name = 'Pharlap and Windows Engine'
type = 'lvBuildSpecAllTargets'
project = '{windows}'
build_spec = 'Engine Release'
dependency_target = 'pharlap'

[[build.steps]]
name = 'Linux32 Engine'
type = 'lvBuildSpecAllTargets'
project = '{linux32}'
build_spec = 'Engine Release'
dependency_target = 'linux_32_ARM'

[[build.steps]]
name = 'Linux64 Engine'
type = 'lvBuildSpecAllTargets'
project = '{linux64}'
build_spec = 'Engine Release'
dependency_target = 'linux_x64'

[[build.steps]]
name = 'SysDef API'
type = 'lvBuildSpec'
project = '{api}'
target = 'My Computer'
build_spec = 'System Definition API'
dependency_target = 'pharlap'

[package]
type = 'nipkg'
name = 'instrument-addon-{veristand_version}'
dev_xml_path = 'Source\Custom Device Instrument Addon.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2019_release_branches = ["master",]
